import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "fitnessApp": "Fitness App",
          "welcomeTitle": "Welcome",
          "welcomeSubtitle": "Join a happy and healthy world",
          "signIn": "SIGN IN",
          "signUp": "SIGN UP",
          "loginTitle": "Welcome back,",
          "loginSubTitle":
              "Step into a world of health and vitality with a simple login",
          "email": "Email",
          "password": "Password",
          "loginSuccessfulySubTitle": "User Logged in successfuly",
          "invalidEmailOrPassword": "Invalid Email or Password",
          "anErrorOccurred": "An error occurred",
          "ok": "Ok",
          "forgetPassword": "Forgete Password",
          "or": "OR ",
          "dontHaveAccount": "Don't have an Account? ",
          "signUpTitle": "Get On ",
          "signUpSubTitle":
              "Join our fitness community and start your transformation...",
          "fullName": "Full Name",
          "gender": "Gender",
          "birthDay": "Birth Day",
          "phoneNumber": "Phone Number",
          "aim": "Aim",
          "heigth": "Heigth",
          "weigth": "Weigth",
          "age": "Age",
          "actvityExtent": "Activity Extent",
          "alreadyHaveAnAccount": "Already have an Account? ",
          "register": "Register",
          "thisEmailIsAlreadyRegistered": "This email is already registered",
          "moreInfo": "More Info",
          "loose": "Loose",
          "gain": "Gain",
          "maintain": "Maintain",
          "pleaseSelectYourAim": "Please select your aim",
          "pleaseSelectYourExerciseLevel": "Please select your exerciseLevel",
          "pleaseSelectYourGender": "Please select your gender",
          "littleToNoExercise": "Little To No Exercise",
          "moderatelyActive": "Moderately Active",
          "veryActive": "Very Active",
          "registrationCompletedSuccessfully":
              "Registration Completed Successfully",
          "internalServerError": "Internal Server Error",
          "home": "Home",
          "gymName": "Gym Name",
          "monthlyPayment": "Monthly Payment",
          "location": "Location",
          "youHaveJoined": "You have joined",
          "failedToJoin": "Failed to join",
          "joinGym": "Join Gym",
          "pleaseTryAgain": "Please try again",
          "categories": "Categories",
          "book": "Book",
          "recentlyAdded": "Recently Added",
          "author": "Author",
          "details": "Details",
          "search": "Search",
          "workoutPlan": "Workout Plan",
          "exercise": "Exercise",
          "chooseExercise": "Choose Exercise",
          "profile": "Profile",
          "hello": "Hello",
          "protein": "Protein",
          "carbs": "Carbs",
          "fat": "Fat",
          "gramsNeeded": "Grams Needed",
          "mealForToday": "MEALS FOR TODAY",
          "foodList": "FOOD LIST",
          "updateProfile": "Update Profile",
          "update": "Update",
          "updatCompletedSuccessfully": "Updat completed successfully",
          "today": "Today",
          "addWorkoutPlan": "Add Workout",
          "chooseWorkout": "Choose Workout",
          "createWorkout": "Create Workout",
          "workoutCreated": "Workout with selected exercises created!",
          "workoutType": "Workout Type",
          "workoutList": "Workout List",
          "workoutNote": "Workout Note",
          "taskComplet": "Task Complet",
          "deleteWorkoutPlan": "Delete Workout Plan",
          "noWorkoutsFound": "No workouts found",
          "close": "Close",
          "easy": "Easy",
          "title": "Title",
          "startDate": "Start Time",
          "endDate": "End Time",
          "colors": "Colors",
          "cancel": "Cancel",
          "yourNextWorkout": "YOUR NEXT WORKOUT",
          "completed": "Completed",
          "todo": "TODO",
          "bmiTitle": "BMI CALCULATOR",
          "calculateBMI": "Calculate BMI",
          "setting": "Setting",
          "bodyFat": "Body Fat",
          "logout": "Logout",
          "yourResults": "Your results",
          "tryAgain": "TRY AGAIN"
        },
        "et_ET": {
          "fitnessApp": "የአካል ብቃት መተግበሪያ",
          "welcomeTitle": "እንኳን ደህና መጡ",
          "welcomeSubtitle": "ወደ ደስተኛ እና ጤነኛ አለም ይቀላቀሉ",
          "signIn": " መግቢያ",
          "signUp": " ይመዝገቡ",
          "loginTitle": "እንኳን ደህና መጡ,",
          "loginSubTitle": "በቀላል ወደ ጤና እና ህይወት ዓለም ይግቡ",
          "email": "ኢሜይል",
          "password": "የይለፍ ቃል",
          "loginSuccessfulySubTitle": "በተሳካ ሁኔታ ገብተዋል።",
          "invalidEmailOrPassword": "የተሳሳተ ኢሜል ወይም የይለፍ ቃል ተጠቅመዋል",
          "anErrorOccurred": "ስህተት ተፈጥሯል",
          "ok": "እሺ",
          "forgetPassword": "የይለፍ ቃል ይሩሱ",
          "or": "ወይም",
          "dontHaveAccount": "መለያ የሎትም?",
          "signUpTitle": "ይመዝገቡ ",
          "signUpSubTitle": "የአካል ብቃት ማህበረሰባችንን ይቀላቀሉ እና ለውጥዎን ይጀምሩ።",
          "fullName": "ሙሉ ስም",
          "gender": "ጾታ",
          "birthDay": "የልደት ቀን",
          "phoneNumber": "ስልክ ቁጥር",
          "aim": "አላማ",
          "heigth": "ቁመት",
          "wigth": "ክብደት",
          "age": "ዕድሜ",
          "actvityExtent": "የተግባር መጠን",
          "alreadyHaveAnAccount": "መለያ አሎት? ",
          "register": "ይመዝገቡ",
          "thisEmailIsAlreadyRegistered": "This email is already registered",
          "moreInfo": "ተጨማሪ መረጃ",
          "loose": "ለመቀነስ",
          "gain": "ለመጨመር",
          "maintain": "ለማስጠበቅ",
          "pleaseSelectYourAim": "እባኮ አላማዎን ይምረጡ",
          "pleaseSelectYourExerciseLevel": "እባክዎ የእንቅስቃሴዎን ደረጃ ይምረጡ",
          "pleaseSelectYourGender": "Please select your gender",
          "littleToNoExercise": "ትንሽ እንቅስቃሴ",
          "moderatelyActive": "መጠነኛ ንቁ",
          "veryActive": "በጣም ከፍ ያለ",
          "registrationCompletedSuccessfully": "ምዝገባው በተሳካ ሁኔታ ተጠናቋል",
          "internalServerError": "Internal Server Error",
          "home": "ዋና ገጽ",
          "gymName": "Gym Name",
          "monthlyPayment": "Monthly Payment",
          "location": "Location",
          "youHaveJoined": "You have joined",
          "failedToJoin": "Failed to join",
          "joinGym": "Join Gym",
          "pleaseTryAgain": "Please try again",
          "categories": "ምድቦች",
          "book": "መጽሐፍ",
          "recentlyAdded": "Recently Added",
          "author": "Author",
          "details": "Details",
          "search": "Search",
          "workoutPlan": "Workout Plan",
          "exercise": "የአካል ብቃት እንቅስቃሴ ",
          "profile": "መገለጫ",
          "hello": "ሰላም",
          "fat": "Fat",
          "protein": "Protein",
          "carbs": "Carbs",
          "gramsNeeded": "Grams Needed",
          "mealForToday": "የዛሬ ምግቦች",
          "foodList": "የምግብ ዝርዝር",
          "updateProfile": "መገለጫ አዘምን",
          "update": "አዘምን",
          "updatCompletedSuccessfully": "Updat completed successfully",
          "today": "ዛሬ",
          "addWorkoutPlan": "እንቅስቃሴን ይጨምሩ",
          "chooseExercise": "Choose Exercise",
          "chooseWorkout": "የአካል ብቃት እንቅስቃሴን ይምረጡ",
          "createWorkout": "የአካል ብቃት እንቅስቃሴ ይፍጠሩ",
          "workoutType": "የአካል ብቃት እንቅስቃሴ ዓይነት",
          "workoutNote": "Workout Note",
          "workoutCreated": "Workout with selected exercises created!",
          "workoutList": "Workout List",
          "taskComplet": "Task Complet",
          "deleteWorkoutPlan": "Delete Workout Plan",
          "noWorkoutsFound": "No workouts found",
          "close": "Close",
          "easy": "Easy",
          "title": "ርዕስ",
          "startDate": "የመነሻ ጊዜ",
          "endDate": "የመጨረሻ ጊዜ",
          "colors": "ቀለሞች",
          "cancel": "ይቅር",
          "yourNextWorkout": "YOUR NEXT WORKOUT",
          "completed": "Completed",
          "todo": "TODO",
          "bmiTitle": "BMI ካልኩሌተር",
          "calculateBMI": "Calculate BMI",
          "bodyFat": "የሰውነት ስብ",
          "setting": "ማቀናበሪያ",
          "logout": "ውጣ",
          "yourResults": "Your results",
          "tryAgain": "TRY AGAIN"
        },
        "et_OR": {
          "fitnessApp": "Appii fiitness",
          "welcomeTitle":
              "Kalaqa keessan tattaaffii guddachaa jiru irratti haa kaa'annu.",
          "signIn": "seena",
          "signUp": "galmaa'aa",
          "loginTitle": "Baga nagaan dhufte,",
          "loginSubTitle": "Addunyaa fayyaa fi jireenyaa salphaatti seeni",
          "email": "email",
          "password": "jecha iccitii",
          "loginSuccessfulySubTitle": "Loggin successfuly",
          "invalidEmailOrPassword": "Invalid Email or Password",
          "anErrorOccurred": "An error occurred",
          "ok": "tole",
          "forgetPassword": "Jecha icciitii dagadhe",
          "or": "YOOKAAN",
          "dontHaveAccount": "Akkaawuntii hin qabduu?",
          "signUpTitle": "irra bu'aa ",
          "signUpSubTitle":
              "Join our fitness community and start your transformation.",
          "fullName": "maqaa guutuu",
          "gender": "Koorniyaa",
          "birthDay": "guyyaa dhalootaa",
          "phoneNumber": "lakkoofsa bilbilaa",
          "aim": "Dhimma",
          "heigth": "Hojjaa",
          "wigth": "Ulfaatina",
          "age": "Umurii",
          "actvityExtent": "Guddina gochaa",
          "alreadyHaveAnAccount": "Akkaawuntii qabda? ",
          "register": "Galmeessuu",
          "thisEmailIsAlreadyRegistered": "This email is already registered",
          "moreInfo": "Odeeffannoo dabalataa",
          "loose": "Loose",
          "gain": "Gain",
          "maintain": "Maintain",
          "pleaseSelectYourAim": "እባኮ አላማዎን ይምረጡ",
          "pleaseSelectYourExerciseLevel": "እባክዎ የእንቅስቃሴዎን ደረጃ ይምረጡ",
          "pleaseSelectYourGender": "Please select your gender",
          "littleToNoExercise": "ትንሽ እንቅስቃሴ",
          "moderatelyActive": "መጠነኛ ንቁ",
          "veryActive": "በጣም ከፍ ያለ",
          "registrationCompletedSuccessfully":
              "Galmeen kun milkaa'inaan xumurameera",
          "internalServerError": "Internal Server Error",
          "home": "mana ",
          "gymName": "Gym Name",
          "monthlyPayment": "Monthly Payment",
          "location": "Location",
          "youHaveJoined": "You have joined",
          "failedToJoin": "Failed to join",
          "joinGym": "Join Gym",
          "pleaseTryAgain": "Please try again",
          "categories": "Ramaddiiwwan",
          "book": "kitaaba",
          "recentlyAdded": "Recently Added",
          "author": "Author",
          "details": "Details",
          "search": "Search",
          "workoutPlan": "Workout Plan",
          "exercise": "Shaakala ",
          "profile": "Ibsama",
          "hello": "Akkam",
          "protein": "Protein",
          "carbs": "Carbs",
          "fat": "Fat",
          "gramsNeeded": "Grams Needed",
          "mealForToday": "Nyaata har'aa",
          "foodList": "Tarree nyaataa",
          "updateProfile": "Profaayila haaromsi",
          "update": "Odeeffannoo dhiyeenyaa",
          "updatCompletedSuccessfully": "Updat completed successfully",
          "today": "Har'a",
          "addWorkoutPlan": "Qaamaa dabaluu",
          "chooseWorkout": "Shaakala filadhu",
          "createWorkout": "Shaakala uumi",
          "workoutType": "Gosa sochii qaamaa",
          "workoutCreated": "Workout with selected exercises created!",
          "workoutList": "Workout List",
          "workoutNote": "Workout Note",
          "taskComplet": "Task Complet",
          "deleteWorkoutPlan": "Delete Workout Plan",
          "noWorkoutsFound": "No workouts found",
          "close": "Close",
          "easy": "Easy",
          "title": "Mata-duree",
          "startDate": "Yeroo ka'umsaa",
          "endDate": "Yeroo darbe",
          "colors": "Halluuwwan",
          "cancel": "ይቅር",
          "yourNextWorkout": "YOUR NEXT WORKOUT",
          "completed": "Completed",
          "todo": "TODO",
          "bmiTitle": "Shallaggii BMI",
          "calculateBMI": "Calculate BMI",
          "bodyFat": "Copha qaamaa",
          "setting": "Setting up gochuu",
          "logout": "Ba'i",
          "yourResults": "Your results",
          "tryAgain": "TRY AGAIN"
        },
        "et_TG": {
          "fitnessApp": "ናይ ብቕዓት ኣፕ",
          "welcomeTitle": "ፈጠራኻ ኣብ ፈተና ምዕባይ ነእትዎ።",
          "signIn": "ኣብ ውሽጢ ምእታው",
          "signUp": "ተመዝገቡ",
          "loginTitle": "እንኳዕ ደሓን መፁ,",
          "loginSubTitle": "ናብ ዓለም ጥዕናን ህይወትን ብቐሊሉ እቶ",
          "email": "ኢመይል",
          "password": "መሕለፊ ቓል",
          "loginSuccessfulySubTitle": "Loggin successfuly",
          "invalidEmailOrPassword": "Invalid Email or Password",
          "anErrorOccurred": "An error occurred",
          "ok": "ደሓን",
          "forgetPassword": "ፓስዎርድ ረሲዐዮ",
          "or": "ወይ",
          "dontHaveAccount": "ኣካውንት የብልካን?",
          "signUpTitle": "ተሰቐል ",
          "signUpSubTitle": "ኣብ ማሕበረሰብ ብቕዓትና ተጸንበሩ እሞ ለውጥኹም ጀምሩ",
          "fullName": "ምሉእ ስም",
          "gender": "ፆታ",
          "birthDay": "በዓል ልደት",
          "phoneNumber": "ቁጽሪ ተሌፎን",
          "aim": "ዕላማ",
          "heigth": "ቁመት",
          "wigth": "ክብደት",
          "age": "ዕድመ",
          "actvityExtent": "መጠን ተግባር",
          "alreadyHaveAnAccount": "ኣካውንት ኣለካ ድዩ? ",
          "register": "ምዝገባ",
          "thisEmailIsAlreadyRegistered": "This email is already registered",
          "moreInfo": "ተወሳኺ ሓበሬታ",
          "loose": "Loose",
          "gain": "Gain",
          "maintain": "Maintain",
          "pleaseSelectYourAim": "እባኮ አላማዎን ይምረጡ",
          "pleaseSelectYourExerciseLevel": "እባክዎ የእንቅስቃሴዎን ደረጃ ይምረጡ",
          "pleaseSelectYourGender": "Please select your gender",
          "littleToNoExercise": "ትንሽ እንቅስቃሴ",
          "moderatelyActive": "መጠነኛ ንቁ",
          "veryActive": "በጣም ከፍ ያለ",
          "registrationCompletedSuccessfully": "እቲ ምዝገባ ብዓወት ተዛዚሙ ኣሎ።",
          "internalServerError": "Internal Server Error",
          "home": "ኣብ ገዛ",
          "gymName": "Gym Name",
          "monthlyPayment": "Monthly Payment",
          "location": "Location",
          "youHaveJoined": "You have joined",
          "failedToJoin": "Failed to join",
          "joinGym": "Join Gym",
          "pleaseTryAgain": "Please try again",
          "categories": "ምድባት",
          "book": "መፅሓፍ",
          "recentlyAdded": "Recently Added",
          "author": "Author",
          "details": "Details",
          "search": "Search",
          "workoutPlan": "Workout Plan",
          "exercise": "ልምምድ ",
          "profile": "መግለፂ",
          "hello": "ሰላም",
          "protein": "Protein",
          "carbs": "Carbs",
          "fat": "Fat",
          "gramsNeeded": "Grams Needed",
          "mealForToday": "ናይ ሎሚ መግቢ",
          "foodList": "ዝርዝር መግቢ",
          "updateProfile": "ፕሮፋይል ኣዘምንዎ።",
          "update": "ኣዘምን",
          "updatCompletedSuccessfully": "Updat completed successfully",
          "today": "ሎምዓንቲ",
          "addWorkoutPlan": "ኣካላዊ ምንቅስቓስ ምውሳኽ",
          "chooseWorkout": "ሓደ ልምምድ ምረጽ",
          "createWorkout": "ልምምድ ምፍጣር",
          "workoutType": "ዓይነት ምንቅስቓስ ኣካላት",
          "workoutCreated": "Workout with selected exercises created!",
          "workoutList": "Workout List",
          "workoutNote": "Workout Note",
          "noWorkoutsFound": "No workouts found",
          "taskComplet": "Task Complet",
          "deleteWorkoutPlan": "Delete Workout Plan",
          "close": "Close",
          "easy": "Easy",
          "title": "ርእሲ",
          "startDate": "ናይ ምብጋስ ግዜ",
          "endDate": "ዝሓለፈ ግዜ",
          "colors": "ሕብርታት",
          "cancel": "ይቅር",
          "yourNextWorkout": "YOUR NEXT WORKOUT",
          "completed": "Completed",
          "todo": "TODO",
          "bmiTitle": "BMI ካልኩሌተር",
          "calculateBMI": "Calculate BMI",
          "bodyFat": "ስብሒ ኣካላት",
          "setting": "ምድላው",
          "logout": "ውጹ",
          "yourResults": "Your results",
          "tryAgain": "TRY AGAIN"
        },
      };
}
