import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          'hey': "HEY ",
          'stay': "STAY ",
          'helathy': "HEALTHY",
          'allworkout': "All workout",
          'no_pain': "No pain No gain Stay Healthy",
          'todays_date': "Today ፡ ",
          'todays_condition_sunligth': "Partly Cloudy  ",
          'biceps_workout': "Biceps Workout",
          'chest_workout': "Chest Workout",
          'back_workout': "Back Workout",
          'shoulder_workout': "Shoulder Workout",
          'leg_workout': "Leg Workout",
          'popular_book': "Popular Book",
          'Philosophy_book': "Philosophy Book",
          'motivation_book': "Motivational Book",
          'boxing_book': "Boxing Book",
          'addWorkoutPlan': " + Create Plan ",
          'title_one': "Title",
          'sub_title_one': "Sub Title",
          'date': "Date",
          'start_date': "Start Date",
          'end_date': "End Date",
          'remind': "Remind",
          'early': "5 minuts early",
          'repeate': "None",
          'color': "Color",
          'preparing': "Preparing...",
          'no_mor_video': "No more video in the list!",
          'video_list': "Video List",
          'no_video_a_head': "No video a head",
          'next': "Next",
          'skip_intro': "Skip Intro",
          'never_traind': "I have never traind ",
          'traind': "Beginner",
          'i_am': "I Am ",
          'about_you': "About You",
          'about_you_info':
              "we want to know more about you, the next steps\n to complet the information",
          'Inactive': "Inactive",
          'Beginner': "Beginner",
          'Advanced': "Advanced",
          'advance': "Advanced",
          'find': "Find",
          'your_workout': "Your Workout",
          'search_workout': "SEARCH WORKOUT",
          'popular_workout': "Popular Workout",
          'popular_books': "Popular Books",
          'hard_workout': "Hard Workout",
          'full_body': "Full Body Workout",
          'simple_workout': "Simple Workout",
          'find_book': "Find",
          'your_book': "your book",
          'search_book': "SEARCH BOOK",
          'today': "Today",
          'task_complet': "Plan Complete",
          'delete_task': "Delete Plan",
          'close': "Close",
          'addWorkoutPlan_info': "Add Plan",
          'createworkoutPlan': "Add Plan",
          'enter_title_one': "Enter your Title",
          'workoutNote': "Enter your Sub Title",
          'detaile': "Details",
          'choose_languge': "Coose Languge",
          'change_thems': "Change Them",
          'change_languge': "Change Languge",
          'email': "Email",
          'name': "Name",
          'password': "Password",
          'sign_in': "Sign in",
          'sign_up': "Sign Up",
          'log_out': "Logout",
          "liked_books": "Liked Book",
          "liked_video": "Liked Video",
          "today_temp": "Today",
          "tmorow_temp": "Tmorow Prediction",
          "check_directory": "Check  directory",
          "details": "Details",
        },
        'et_ET': {
          'hey': "b ፡ ",
          'stay': "በጤና ",
          'helathy': "ይቆዩ",
          'allworkout': "ሁሉም ስራዎች።",
          'no_pain': "በብልሃት ይስሩ ከምንም ህመም ከምንም ስብ ፡ ጤነኛ ይሁኑ",
          'todays_date': "የዛሬው ቀን ፡ ",
          'todays_condition_sunligth': "ከፊል ደመናማ ",
          'biceps_workout': "የፊት እጅ     ",
          'chest_workout': "የደረት       ",
          'back_workout': "የጀርባ        ",
          'shoulder_workout': "የትከሻ       ",
          'leg_workout': "የእግር",
          'popular_book': "ታዋቂ መጽሃፎች",
          'Philosophy_book': "ፍልስፍና",
          'motivation_book': "አነቃቂ",
          'boxing_book': "የቡጢ ስፖርት",
          'addWorkoutPlan': " + ተግባር መዝግብ",
          'title_one': "ርዕስ",
          'sub_title_one': "ንዑስ ርእስ",
          'date': "ቀን",
          'start_date': "የመጀምሪያ ሰአት",
          'end_date': "የመጨረሻ ሰአት",
          'remind': "አስታዉሰኝ",
          'early': "5 ደቂቃ ቡሁላ",
          'repeate': "ይደጋገም",
          'color': "ቀለማት",
          'createworkoutPlan': "ተግባር ይመዝገብ",
          'preparing': "እየተዘጋጀ ነው...",
          'no_mor_video': "ሌላ ተጨማሪ ምስሎች በዝርዝሩ ላይ የሉም!",
          'video_list': "የምስሎች ዝርዝር",
          'no_video_a_head': "ከዚህ በላይ ምስሎች የሉም",
          'next': "ቀጣይ",
          'skip_intro': "መግቢያውን ለማለፍ",
          'never_traind': "ከዚህ በፊት ሞክሬ አላውቅም ",
          'traind': "ጀማሪ ነኝ",
          'advance': "ብዙ ግዜ ሰርቻለሁ",
          'i_am': "እኔ ",
          'about_you_info':
              "ስለ አርሶ በደንብ ማወቅ እንፈልጋለን ፡ ስለእርሶ ይንገሩን \n መረጃዉን  ይሙሉ ",
          'about_you': "ስለ እርሶ",
          'Inactive': "",
          'Beginner': "",
          'Advanced': "",
          'find': "ስፖርቶችን",
          'your_workout': "ፈልግ",
          'search_workout': "ስፖርቶችን ፈልግ",
          'popular_workout': "ታዋቂ ስፖርቶች",
          'popular_books': "ታዋቂ መጽሃፎች",
          'hard_workout': "ከባድ ስፖርቶች",
          'full_body': "ለሁሉም ሰዉነት",
          'simple_workout': "ቀላል ስፖርቶች",
          'find_book': "መጽሀፍትን",
          'your_book': "ፈልግ",
          'search_book': "መጽሀፍትን ፈልግ",
          'today': "ዛሬ",
          'task_complet': "ተግባሩ ተጠናቋል",
          'delete_task': "ተባሩ ይጥፋ",
          'close': "ዝጋ",
          'addWorkoutPlan_info': "ተግባር መመዝገቢያ",
          'enter_title_one': "ርእሱን ያስገቡ",
          'workoutNote': "ንኡስ እርእሱን ያስገቡ",
          'detaile': "ዝርዝር መረጃ ",
          'choose_languge': "ቋንቋ ቀይር",
          'choose_them': "ቀለም ቀይር ",
          'change_thems': "ማቀናበሪያ ይቀይሩ",
          'change_languge': "ቋንቋ ቀይር",
          'email': "ኢሜል",
          'name': "ስም",
          'password': "የይለፍ ቃል",
          'sign_in': "ይግቡ ",
          'log_out': "ይውጡ",
          'sign_up': "ይመዝገቡ",
          'forgot_password': "የይለፍ ቃል ይቀይሩ",
          "liked_books": "የወደዱት መጽሃፍ",
          "liked_video": "የወደዱት ስራዎች",
          "today_temp": "የዛሬ   ",
          "tmorow_temp": "የነገ ግምት   ",
          "check_directory": "ማውጫ ይፈትሹ",
          "details": "ዝርዝሮች መረጃ",
        },
        'et_OR': {
          'hey': "Akkam ፡ ",
          'stay': "Fayyaa keessatti ",
          'helathy': "Turuu",
          'allworkout': "Hojii hunda ",
          'no_pain':
              "Ogeessa hojjedhu, dhukkubbii hin qabu, cooma hin qabu, fayyaa ta'i",
          'todays_date': "Guyyaa har'aa፡ ",
          'todays_condition_sunligth': "Gara tokkoon duumessa፡ ",
          'biceps_workout': "Harka fuulduraa    ",
          'chest_workout': "Laphee       ",
          'back_workout': "Dugduubee        ",
          'shoulder_workout': "Gateettii       ",
          'leg_workout': "miilla     ",
          'popular_book': "Kitaabota beekamoo",
          'Philosophy_book': "Falaasama",
          'motivation_book': "Kan nama kakaasu",
          'boxing_book': "Ispoortii harkaa",
          'addWorkoutPlan': " + Galmee gochaa",
          'title_one': "Mata-duree",
          'sub_title_one': "Mata duree xiqqaa",
          'date': "guyyaa",
          'start_date': "Yeroo jalqabaa",
          'end_date': "Sa'aatii dhumaa",
          'remind': "Na yaadachiisaa",
          'early': "Daqiiqaa 5 booda",
          'repeate': "Irra-deebi'uu",
          'color': "Halluuwwan",
          'createworkoutPlan': "Faankishinii galmeessuu",
          'preparing': "Qophaa'aa jira...",
          'no_mor_video': "Suuraan kana booda tarree kana keessa hin jiru!",
          'video_list': "Tarree fakkiiwwanii",
          'no_video_a_head': "Kana booda suuraan hin jiru",
          'next': "Kan itti aanu",
          'skip_intro': "Seensa bira darbuuf",
          'never_traind': "Kanaan dura yaalee hin beeku ",
          'traind': "Ani nama jalqabaati",
          'advance': "Yeroo hedduu hojjedheera",
          'i_am': "An ",
          'about_you_info':
              "Waa'ee kee caalaatti baruu barbaanna.Waa'ee kee nuuf himi \n Odeeffannoo guutaa",
          'about_you': "Waa'ee keessanii",
          'Inactive': "",
          'Beginner': "",
          'Advanced': "",
          'find': "Ispoortii",
          'your_workout': "bira ga'uu",
          'search_workout': "Ispoortii barbaadi",
          'popular_workout': "Ispoortii beekamaa",
          'popular_books': "Kitaabota beekamoo",
          'hard_workout': "Ispoortii ulfaataa",
          'full_body': "Hundaaf",
          'simple_workout': "Ispoortii salphaa",
          'find_book': "Kitaabota",
          'your_book': "bira ga'uu",
          'search_book': "Kitaabota barbaadi",
          'today': "Har'a",
          'task_complet': "Hojiin xumuramee jira",
          'delete_task': "Garbichi haa badu",
          'close': "Cufuu",
          'addWorkoutPlan_info': "Galmee hojii",
          'enter_title_one': "Mata duree galchi",
          'workoutNote': "Mata duree xiqqaa galchi",
          'detaile': "Odeeffannoo bal'aa ",
          'choose_languge': "Afaan jijjiiri",
          'choose_them': "Halluu jijjiiri ",
          'change_thems': "Sajoo jijjiiri",
          'change_languge': "Afaan jijjiiri",
          'email': "Imeelii",
          'name': "Maqaa",
          'password': "jecha iccitii",
          'sign_in': "Seenuu ",
          'log_out': "Ba'aa",
          'sign_up': "Galmeessuu",
          'forgot_password': "Jecha icciitii jijjiiri",
          "liked_books": "Kitaaba jaallattan",
          "liked_video": "Hojiiwwan isin jaallattan",
          "today_temp": "Har'a   ",
          "tmorow_temp": "Tilmaama boruu   ",
          "check_directory": "Galmee ilaali ",
          "details": "gadifageenyaan",
        },
        'et_TG': {
          'hey': "ሰላም ፡ ",
          'stay': "ኣብ ጥዕና ",
          'helathy': "ፅናሕ",
          'allworkout': "ኩሉ ስራሕ።",
          'no_pain': " በሊሕ ስራሕ፡ ቃንዛ የለን፡ ስብሒ የለን፡ ጥዕና ዘለዎ ኩን።",
          'todays_date': "ናይ ሎሚ ዕለት ፡ ",
          'todays_condition_sunligth': "ብኸፊል ደበናዊ እዩ።፡ ",
          'biceps_workout': "ቅድሚት ኢድ   ",
          'chest_workout': "አፍ-ልቢ       ",
          'back_workout': "ድሕረ ባይታ        ",
          'shoulder_workout': "መንኰብ       ",
          'leg_workout': "እግሪ   ",
          'popular_book': "ህቡባት መጻሕፍቲ ",
          'Philosophy_book': "ፍልስፍና ",
          'motivation_book': "ምልዕዓል ",
          'boxing_book': "ፊስት ስፖርት",
          'addWorkoutPlan': " + መዝገብ ተግባር",
          'title_one': "ርእሲ",
          'sub_title_one': "ንኡስ ኣርእስቲ",
          'date': "መዓልቲ",
          'start_date': "ናይ ምጅማር ግዜ",
          'end_date': "ናይ መወዳእታ ሰዓት",
          'remind': "ኣዘኻኽረኒ ",
          'early': "ድሕሪ 5 ደቓይቕ",
          'repeate': "ደገመ",
          'color': "ሕብርታት",
          'createworkoutPlan': "ናይ መዝገብ ተግባር",
          'preparing': "ምድላው...",
          'no_mor_video': "ድሕሪ ሕጂ ኣብቲ ዝርዝር ስእልታት የለን!",
          'video_list': "ዝርዝር ምስልታት",
          'no_video_a_head': "ካብዚ ንላዕሊ ምስልታት የለን",
          'next': "ቀፃሊ",
          'skip_intro': "ነቲ መእተዊ ንምሕላፍ",
          'never_traind': "ቅድሚ ሕጂ ፈቲነ ኣይፈልጥን ",
          'traind': "ኣነ ጀማሪ እየ",
          'advance': "ብዙሕ ግዜ ሰሪሐ እየ",
          'i_am': "ኣነ ",
          'about_you_info':
              "ብዛዕባኻ ዝያዳ ክንፈልጥ ንደሊ ብዛዕባ ነብስኻ ንገረና። \n ነቲ ሓበሬታ ምልኣዮ ",
          'about_you': "ብዛዕባኻ",
          'Inactive': "",
          'Beginner': "",
          'Advanced': "",
          'find': "ስፖርት",
          'your_workout': "ምድላይ",
          'search_workout': "ስፖርት ድለዩ",
          'popular_workout': "ህቡብ ስፖርት",
          'popular_books': "ህቡባት መጻሕፍቲ",
          'hard_workout': "ከበድቲ ስፖርት",
          'full_body': "ንኹሉ ሰብ",
          'simple_workout': "ቀለልቲ ስፖርት",
          'find_book': "መጽሓፍቲ",
          'your_book': "ምድላይ",
          'search_book': "መጽሓፍቲ ድለዩ",
          'today': "ሎምዓንቲ",
          'task_complet': "እቲ ዕማም ተዛዚሙ",
          'delete_task': "እቲ ባርያ ይጠፍእ",
          'close': "ዕፁው",
          'addWorkoutPlan_info': "ዕማም መዝገብ",
          'enter_title_one': "ኣርእስቲ ኣእትዉ",
          'workoutNote': "ንኡስ ኣርእስቲ ኣእትዉ",
          'detaile': "ዝርዝር ሓበሬታ ",
          'choose_languge': "ቋንቋ ምቕያር",
          'choose_them': "ሕብሪ ምቕያር ",
          'change_thems': "ነቲ ቅጥዒ ቀይሮ",
          'change_languge': "ቋንቋ ምቕያር",
          'email': "ኢመይል",
          'name': "ሽም",
          'password': "መሕለፊ ቓል",
          'sign_in': "ኣእትው ",
          'log_out': "ውጹ",
          'sign_up': "ምዝገባ",
          'forgot_password': "ፓስዎርድ ምቕያር",
          "liked_books": "ዝፈትዋ መጽሓፍ",
          "liked_video": "እቶም ትፈትዎም ስራሕቲ",
          "today_temp": "ሎምዓንቲ   ",
          "tmorow_temp": "ናይ ጽባሕ ግምት   ",
          "check_directory": "ማህደር ምፍታሽ ",
          "details": "ዝርዝራት",
        }
      };
}
